name: CD_workflow_AMI
run-name: Build and store AMI on gcloud with packer
on:
  pull_request:
    types: [closed]
  workflow_dispatch:
env:
  PRODUCT_VERSION: "latest"

jobs:
  build-ami-with-packer:
    if: ${{ github.event.pull_request.merged }} ||  ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "current path"
        run: "pwd"
      - name: "current files in directory"
        run: |
          cd /home/runner/work/webapp-fork/
          ls
      - uses: montudor/action-zip@v1
        with:
          args: zip webapp.zip webapp-fork
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/"

      - name: Run `packer fmt`
        run: "packer fmt -check ./packer/"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./packer/"

      - name: Run `packer build`
        id: build
        run: "packer build ./packer/"
