name: CD_workflow_AMI
run-name: Build and store AMI on gcloud with packer
on:
  pull_request:
    types: [closed]
  workflow_dispatch:
env:
  PRODUCT_VERSION: "latest"

jobs:
  build-ami-with-packer:
    if: ${{ github.event.pull_request.merged }} ||  ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "install zip package"
        run: "sudo apt install zip"
      - name: "zip the repository"
        run: |
          zip -r webapp.zip .
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: install dependencies
        run: npm i
      - name: Install PostgresSQL
        run: |
          sudo apt install -y postgresql-14 postgresql-client-14
          sudo systemctl enable postgresql
          sudo systemctl start postgresql
      - name: change passoword of user
        run: sudo -u postgres psql -c "ALTER USER ${{ secrets.DB_USERNAME }} PASSWORD '${{ secrets.DB_PASSWORD }}';"
      - name: Create the .env file
        run: |
          cat << EOF > .env
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_PORT=${{ secrets.DB_PORT }}
          PORT=${{ secrets.PORT }}
          DB_HOST=${{ secrets.DB_HOST }}
          EOF
          echo ".env file created with the specified content."
      - run: cat .env
      - name: Run tests
        run: npm test
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/"

      - name: Run `packer fmt`
        run: "packer fmt -check ./packer/"

      - name: Run `packer validate`
        id: validate
        run: "packer validate -syntax-only ./packer/"

      - name: Run `packer build`
        id: build
        run: "packer build -var-file=./packer/var.pkrvars.hcl  ./packer/"
