name: CI_workflow_packer
run-name: Validate packer file and format
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
env:
  PRODUCT_VERSION: "latest"

jobs:
  vaidate-packer-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer fmt`
        id: init
        run: "packer fmt ."

      - name: Run `packer init`
        id: init
        run: "packer init"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ."
