name: CI_workflow_packer
run-name: Validate packer file and format
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
env:
  PRODUCT_VERSION: "latest"

jobs:
  validate-packer-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}
      - name: create .env and webapp.zip
        run: |
          touch webapp.zip
          touch .env
      - name: Run `packer init`
        id: init
        run: "packer init ./packer/"

      - name: Run `packer fmt`
        run: "packer fmt -check ./packer/"

      - name: Run `packer validate`
        id: validate
        run: "packer validate -var-file=./packer/var.pkrvars.hcl ./packer"
