name: CI workflow
run-name: Validate successful compilation of applicaiton 🚀
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  validate-app-compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: install dependencies
        run: npm i
      - run: npm test
      - run: npm start &
      - run: lsof -i :3000 | grep "node" | awk '{print $1}' | tail -n 1 | (read command; if [ "$command" = "node" ]; then echo "Node.js process is running"; exit 0; else echo "Not a Node.js process"; exit 1; fi)
      - name: stop node process
        run: kill $(lsof -t -i :3000)
